### PR TITLE
Migrate `generate` to Slash Commands

### PR DESCRIPTION
**Pull request by Starlight220**

### CODE REVIEW

**Comment by cwarwicker** [comment]
I think this works. Is there any way to have the strings as language strings, rather than hard-coded as English? Or will that not work?

**Comment by Starlight220** [comment]
As far as I know, translations of Slash Commands isn't possible right now but is on Discord's roadmap. As far as I know, Slash Command metadata is globally set on init, and can't be dynamically altered: this influences translations and some other stuff as well (for instance, letting the user select a project from their registered projects list; there might be something else we can use for that though).

**Comment by cwarwicker** [comment]
So, if we added another type of generation later, would this option menu not include it?

**Comment by Starlight220** [comment]
Changes can be made when restarting the bot. My point was that the options list cannot be created dynamically at runtime according to server/channel context, user, etc.
There is some sort of a `Menu` type interaction that can be dynamic, but I don't think that it fits the `generate` command. I was thinking of using it for the `project` commands and such though, assuming that it's appropriate for that command (as said, I haven't looked at it yet).

**Comment by cwarwicker** [comment]
This currently has conflicts with master. Could you resolve them and patch?

**Comment by Starlight220** [comment]
Done

**Pull request merged**
