### PR TITLE
Refactor and migrate `/project`

### LINKED ISSUE #109: Project Hiatus
Put a project on hiatus for when it's not actively being worked on but isn't abandoned

### LINKED ISSUE #132: [project] Add more status options
`hiatus` (#109), `rewriting`, `rejected`, `submitted`, `accepted`, maybe some others?

### PR DESCRIPTION
**Pull request by Starlight220**
resolves #109
resolves #132

### CODE REVIEW

**Comment by Starlight220** [comment]
Needs testing.
`/project list` needs pagination and filter view. Maybe postpone the dynamic component-based view to later?

**Comment by enigmalea** [comment]
I had some thoughts about embeds/pagination... and also some difficulties posed by adding it, but I figured I'd share. I think one of the easiest ways to keep it compact would be to do 5-10 projects per page, with project title and word count going into a field title and status/genre going into a field description. Something like this:

image

Now, you'll run into a mal-formed embed if you don't provide a description for every title, but if the user hasn't set a status/genre, but you can use unicode character `\u200B` to produce a blank space in the embed that discord will still consider a character, so the embed will still send.

BUT we run into pagination issues. So far I've tried two pagination utilities with my own bot and disliked them both for different reasons:
- [discord.py menus ext](https://github.com/Rapptz/discord-ext-menus) - Hasn't been an update since July but not officially archived like discord.py. Unlikely to be additional updates, obviously. The big draw back to this is that the bot doesn't REMOVE the reactions as you click. Super annoying interface.
- [disputils](https://github.com/LiBa001/disputils) - I could not for the LIFE of me figure out how to auto generate an embed with this, and ended up hardcoding everything, but I'm a baby coder. And maybe someone better than me can figure it out.

However, I've been taking a look at [Pycord](https://github.com/Pycord-Development/pycord) recently, and it looks like you can just install it over top of discord.py and keep your same syntax. I haven't played with it yet, but their [docs](https://docs.pycord.dev/en/master/index.html) do have some info on [pagination](https://docs.pycord.dev/en/master/ext/pages/index.html?highlight=pagination), and it also supports threads. Stability is a question, however, as I'm not super familiar with the project and I know a bunch of people have abandoned discord.py related libraries in favor of newer, shinier things.

**Comment by enigmalea** [comment]
Also had a thought about `filter`. Since you're using discord-py-slash-commands module, maybe use **Selects** for a filter view?

`\projects view` -> WB responds with a select menu consisting of the statuses and genres from the user's projects in an -> user selects what to filter -> embed is produced.

Unsure if this is too complicated, but it may reduce the need for error handling if the user can only input statuses and genres which actually exist for them.

**Comment by Starlight220** [comment]
Sorry for the delayed response!

I think that interactions.py (the lib we're using) has some pagination extensions available once we update to v4. As for `filter`, I think that I've tried implementing what you're suggesting and ran into some issues; once again, I think they're solvable with a v4 extension.

v4 cogs are expected to be released at the end of Feb, and we can't upgrade before that. The plan right now is to finish migrating stuff to v3; we'll probably add all the bells and whistles when we upgrade to v4.

**Pull request merged**
